spring:
  application:
    name: ms-identity
  server:
    port: 8081
    servlet:
      context-path: /ms-identity
  data:
    mongodb:
      uri: mongodb://mongo:mysecretpassword@localhost:27017/identity_db?authSource=admin




