spring:
  application:
    name: ms-identity
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  servlet:
    context-path: /ms-identity
data:
  mongodb:
    uri: mongodb://admin:adminpassword@localhost:27020/identity_db?authSource=admin
management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    consul:
      enabled: true
    mongo:
      enabled: true



jwt:
  secret: 9rvuHvQY8fPmkQoVdPo7OQg4NYrmcJkjsYYBZj5gL0A=
  access-token-expiration: 900000
  refresh-token-expiration: 604800000
