spring:
  application:
    name: ms-identity
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ms-identity
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

  servlet:
    context-path: /ms-identity
data:
  mongodb:
    uri: mongodb://mongodb:mongodbd@localhost:27018/identity_db?authSource=admin
management:
  endpoints:
    web:
      exposure:
        include: health,info
jwt:
  secret: 9rvuHvQY8fPmkQoVdPo7OQg4NYrmcJkjsYYBZj5gL0A=
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

server:
  port: 8093