spring:
  application:
    name: ms-identity
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ms-identity
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

  servlet:
    context-path: /ms-identity
data:
  mongodb:
    uri: mongodb://mongodb:mongodbd@localhost:27018/identity_db?authSource=admin
management:
  endpoints:
    web:
      exposure:
        include:  prometheus,metrics
  metrics:
    export:
      prometheus:
      # Bu hissəni əlavə etməyə ehtiyac yoxdur, çünki artıq Prometheus avtomatik olaraq aktiv olur.
  endpoint:
    prometheus:
      enabled: true

jwt:
  secret: 9rvuHvQY8fPmkQoVdPo7OQg4NYrmcJkjsYYBZj5gL0A=
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

node-exporter:
  image: prom/node-exporter:latest
  container_name: node-exporter
  ports:
    - "9100:9100"
  networks:
    - app-network

server:
  port: 8093

