global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'eureka-server'
    static_configs:
      - targets: ['localhost:8762'] # Əgər eureka-server konteyner adından istifadə etmək işləmir

  - job_name: 'gateway'
    static_configs:
      - targets: ['localhost:8081']

  - job_name: 'ms-account'
    static_configs:
      - targets: ['localhost:8085']

  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: 'ms-identity'
    static_configs:
      - targets: ['localhost:8084']

  - job_name: 'ms-transfer'
    static_configs:
      - targets: ['localhost:8090']

  - job_name: 'ms-currency'
    static_configs:
      - targets: ['localhost:8083']
