services:
  mongodb:
    container_name: my_mongo
    image: mongo:latest
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - "27018:27017"
    networks:
      - app-network
    volumes:
      - mongodb_data:/data/db

  ms-identity:
    image: ms-identity
    container_name: ms-identity-app
    env_file:
      - .env
    environment:
      SPRING_APPLICATION_JSON: '{
                "spring.data.mongodb.uri" : "mongodb://mongo:mysecretpassword@mongodb:27017/identity_db?authSource=admin"
              }'
    ports:
      - "8081:8080"
    networks:
      - app-network
    depends_on:
      - mongodb



networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: