spring:
  application:
    name: consul-module # Service name
  cloud:
    consul:
      host: localhost # Consul server host
      port: 8500      # Consul server port
      discovery:
        enabled: true # Enable service discovery
        prefer-ip-address: true # Use the IP address for service registration
      config:
        enabled: true # Enable Consul Config
        default-context: application # Read from the "application" context in Consul
        profile-separator: "-" # Profile separator
  config:
    import: "optional:consul:" # Required for loading configuration from Consul

management:
  endpoints:
    web:
      exposure:
        include: health # Enable health endpoint
  health:
    consul:
      enabled: true # Enable health check for Consul
server:
  port: 8092
