spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-identity
          uri: lb://MS-IDENTITY
          predicates:
            - Path=/api/v1/auth/**
        - id: ms-account
          uri: lb://ms-account
          predicates:
            - Path=/api/account/**
        - id: ms-transfer
          uri: lb://ms-transfer
          predicates:
            - Path=/api/v1/transfers
        - id: ms-currency
          uri: lb://ms-currency
          predicates:
            - Path=/api/currency/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
