spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-identity
          uri: lb://MS-IDENTITY
          predicates:
            - Path=/api/v1/auth/**
        - id: ms-account
          uri: lb://MS-ACCOUNT
          predicates:
            - Path=/account/**
        - id: ms-transfer
          uri: lb://MS-TRANSFER
          predicates:
            - Path=/api/v1/transfers/**
        - id: currency-service
          uri: lb://CURRENCY-SERVICE
          predicates:
            - Path=/api/currency/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: prometheus,metrics
  metrics:
    export:
      prometheus:
      # Bu hissəni əlavə etməyə ehtiyac yoxdur, çünki artıq Prometheus avtomatik olaraq aktiv olur.
  endpoint:
    prometheus:
      enabled: true
