spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bff-route
          uri: lb://bff
          predicates:
            - Path=/bff/**

        - id: ms-identity-route
          uri: lb://ms-identity
          predicates:
            - Path=/identity/**

consul:
  discovery:
    enabled: true
    prefer-ip-address: true
    register: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
