spring:
  application:
    name: currency-service
  cache:
    type: caffeine
  task:
    scheduling:
      pool:
        size: 5
  main:
    allow-bean-definition-overriding: true

exchange:
  api:
    url: https://api.exchangeratesapi.io
    key: 1f454a163f0d011d6f8e52fc2e986d97

feign:
  hystrix:
    enabled: true

server:
  port: 8087

logging:
  level:
    root: INFO
    com.example: DEBUG
