spring:
  application:
    name: currency-service
  cache:
    type: caffeine
  task:
    scheduling:
      pool:
        size: 5
  main:
    allow-bean-definition-overriding: true

exchange:
  api:
    url: https://api.exchangeratesapi.io
    key: e158906973b85c723b5bba883466eba9

feign:
  hystrix:
    enabled: true

server:
  port: 8087

logging:
  level:
    root: INFO
    com.example: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true