spring:
  application:
    name: currency-service
  cache:
    type: caffeine
  task:
    scheduling:
      pool:
        size: 5
  main:
    allow-bean-definition-overriding: true

exchange:
  api:
    url: https://api.exchangeratesapi.io
    key: e158906973b85c723b5bba883466eba9

feign:
  hystrix:
    enabled: true

server:
  port: 8087

logging:
  level:
    root: INFO
    com.example: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ms-currency
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include:  prometheus,metrics
  metrics:
    export:
      prometheus:
      # Bu hissəni əlavə etməyə ehtiyac yoxdur, çünki artıq Prometheus avtomatik olaraq aktiv olur.
  endpoint:
    prometheus:
      enabled: true
