spring:
  application:
    name: ms-transfer # Microservice name for Eureka registration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Aba32835
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true # Optional: enables logging of SQL queries
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ms-transfer
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

transfer:
  queue: transfer.queue # Queue to listen to
  exchange: transfer.exchange
  routingKey: transfer.routingKey
server:
  port: 8086
management:
  endpoints:
    web:
      exposure:
        include:  prometheus,metrics
  metrics:
    export:
      prometheus:
      # Bu hissəni əlavə etməyə ehtiyac yoxdur, çünki artıq Prometheus avtomatik olaraq aktiv olur.
  endpoint:
    prometheus:
      enabled: true
