spring:
  application:
    name: ms-transfer # Microservice name for Eureka registration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Aba32835
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true # Optional: enables logging of SQL queries
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka Server URL
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ms-transfer # Hostname for the microservice

transfer:
  queue: transfer.queue # Queue to listen to
  exchange: transfer.exchange
  routingKey: transfer.routingKey
server:
  port: 8086
