spring:
  application:
    name: ms-transfer # Microservice name for Eureka registration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

transfer:
  queue: transfer.queue # Queue to listen to
  exchange: transfer.exchange
  routingKey: transfer.routingKey

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka Server URL
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ms-transfer # Hostname for the microservice
