spring:
  application:
    name: ms-account

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Aba32835
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ms-account
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

account:
  queue: account.queue
  exchange: account.exchange
  routingKey: account.routingKey
server:
  port: 8095

management:
  endpoints:
    web:
      exposure:
        include: prometheus,metrics
  metrics:
    export:
      prometheus:
  endpoint:
    prometheus:
      enabled: true
